version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: t3g
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "techno3gamma@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "thalaforareason"
    ports:
      - "8080:80"
    depends_on:
      - db
  